name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        server-id: github
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build with Maven
      run: mvn --quiet --show-version --batch-mode verify
      env:
        MAVEN_USERNAME: ${{ vars.PACKAGES_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.PACKAGES_PASSWORD }}
